### ISSUE TITLE
修改的qt creator版本

### ISSUE THREAD

**Issue by SurnameX** [VelsonWang/AppDemo#1]
你好
请问你修改的qtcreator对应的版本是多少呢，想通过qtcreator的源代码与之对比一下，加深学习。谢谢。

**Comment by VelsonWang** [comment]
4.x版本，具体的哪一个版本我不太记得了

**Comment by SurnameX** [comment]
不好意思，看代码不仔细，根目录下的AppDemo.pri文件有详细标注，得益于没看到(...)，下载了几个版本在源代码中看到了qtcreator.pri中有标注，才反应过来根目录中应该有类似的文件。
